language: cpp
sudo: required
os: linux
dist: bionic
#matrix:
#  include:
#    - os: linux
#      env: COMPILER_NAME=gcc CXX=g++-7 CC=gcc-7
#    - os: linux
#      env: COMPILER_NAME=clang CXX=clang++-7.0 CC=clang-7.0
compiler:
  - clang
  - gcc
before_script:
  - sudo apt-get -qq update
  - sudo apt-get install -y  libx11-xcb-dev libxrandr-dev
  - export VK_VERSION=1.1.126.0
  - wget -O vulkansdk-linux-x86_64-$VK_VERSION.tar.gz https://sdk.lunarg.com/sdk/download/$VK_VERSION/linux/vulkansdk-linux-x86_64-$VK_VERSION.tar.gz
  - tar zxf vulkansdk-linux-x86_64-$VK_VERSION.tar.gz
  - export VULKAN_SDK=$TRAVIS_BUILD_DIR/$VK_VERSION/x86_64
script:
  # show OS/compiler version
  - uname -a
  - $CXX --version
  # compile and execute 
  - cmake --version
  #- git submodule update --init --recursive
  - mkdir -p build && cd build
  - cmake ..
  - cmake --build . --target package --config Release -- -j4
